// Login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const UPDATE_LOGIN_DETAILS = "UPDATE_LOGIN_DETAILS";
export const CHANGE_LOGIN_FORM = "CHANGE_LOGIN_FORM";
export const SET_ERROR_MESSAGE = "SET_ERROR_MESSAGE";
// Alert
export const GET_ALERT_SUCCESS = "GET_ALERT_SUCCESS";
export const SNOOZE_ALERT_SUCCESS="SNOOZE_ALAERT_SUCCESS";
export const DISMISS_ALERT_SUCCESS="DISMISS_ALERT_SUCCESS";
 

